name: Package Application with Pyinstaller (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@python3.10
      with:
        path: src
        spec: thing.spec
        gooey: false

    - uses: actions/upload-artifact@v4
      with:
        name: thing
        path: src/dist/linux
