name: Package Application with Pyinstaller (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
        spec: thing.spec

    - uses: actions/upload-artifact@v4
      with:
        name: thing.exe
        path: src/dist/windows
